<?php

namespace Desarrolla2\Bundle\BlogBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Desarrolla2\Bundle\BlogBundle\Document\Banner;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends DocumentRepository
{

    /**
     * Retrieve a random active Banner
     *
     * @return bool|Banner
     */
    public function getRandomActive()
    {
        $em = $this->getDocumentManager();
        $query = $em->createQueryBuilder()->field('published')->equals(true)->getQuery();

        $banners = array();
        $items = $query->execute();
        if (!$items) {
            return false;
        }
        foreach ($items as $banner) {
            $weight = $banner->getWeight();
            for ($i = 0; $i < $weight; $i++) {
                $banners[] = $banner;
            }
        }

        shuffle($banners);

        return array_pop($banners);
    }

    /**
     *
     * @return \Doctrine\ODM\MongoDB\Query\Builder
     */
    public function getQueryBuilderForFilter()
    {
        $em = $this->getDocumentManager();
        $qb = $em->createQueryBuilder();
        $qb->sort('createdAt', 'DESC');

        return $qb;
    }
}
