<?php

namespace Desarrolla2\Bundle\BlogBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Desarrolla2\Bundle\BlogBundle\Model\LinkStatus;
use DateTime;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends DocumentRepository
{

    /**
     *
     * @return array
     */
    public function getActive()
    {
        $query = $this->getQueryForGetActive();

        return $query->getQuery()->execute();
    }

    /**
     *
     * @return \Doctrine\ODM\MongoDB\Query\Builder
     */
    public function getQueryForGetActive()
    {
        $em = $this->getDocumentManager();
        $qb = $em->createQueryBuilder();

        $qb->field('published')->equals(LinkStatus::PUBLISHED);
        $qb->sort('createdAt', 'DESC');

        return $qb;
    }

    /**
     *
     * @return array
     */
    public function getActiveOrdered()
    {
        $query = $this->getQueryForGetActiveOrdered();

        return $query->getQuery()->execute();
    }

    /**
     *
     * @return \Doctrine\ODM\MongoDB\Query\Builder
     */
    public function getQueryForGetActiveOrdered()
    {
        $em = $this->getDocumentManager();
        $query = $em->createQuery(
            ' SELECT l FROM BlogBundle:Link l ' .
            ' WHERE l.isPublished = ' . LinkStatus::PUBLISHED .
            ' ORDER BY l.name ASC '
        );

        return $query;
    }

    /**
     *
     * @return \Doctrine\ODM\QueryBuilder
     */
    public function getQueryBuilderForFilter()
    {
        $em = $this->getDocumentManager();
        $qb = $em->createQueryBuilder();
        $qb
            ->select('l')
            ->from('BlogBundle:Link', 'l')
            ->orderBy('l.updatedAt', 'DESC');

        return $qb;
    }

    public function getOneBySlug($slug)
    {
        $em = $this->getDocumentManager();
        $query = $em->createQuery(
            ' SELECT l FROM BlogBundle:Link l ' .
            ' WHERE l.slug = :slug '
        )
            ->setParameter('slug', $slug);

        return $query->getOneOrNullResult();
    }

    /**
     * Count published elements from date
     *
     * @param  DateTime $date
     * @return int
     */
    public function countFromDate(DateTime $date)
    {
        $em = $this->getDocumentManager();
        $query = $em->createQuery(
            ' SELECT COUNT(l) FROM BlogBundle:Link l ' .
            ' WHERE l.isPublished = ' . LinkStatus::PUBLISHED .
            ' AND l.createdAt >= :date '
        )
            ->setParameter('date', $date);

        return $query->getSingleScalarResult();
    }

    /**
     *
     * @param  DateTime $date
     * @param  int      $limit
     * @return array
     */
    public function getMoreActiveFromDate(DateTime $date, $limit = 10)
    {
        $em = $this->getDocumentManager();
        $query = $em->createQuery(
            ' SELECT l ' .
            ' FROM BlogBundle:Link l ' .
            ' JOIN l.Post p ' .
            ' WHERE l.isPublished = ' . LinkStatus::PUBLISHED .
            ' AND l.createdAt >= :date ' .
            ' GROUP BY l ' .
            ' ORDER BY n DESC '
        )
            ->setParameter('date', $date)
            ->setMaxResults($limit);
    }
}
