<?php

namespace Desarrolla2\Bundle\BlogBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Desarrolla2\Bundle\BlogBundle\Model\LinkStatus;
use DateTime;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends DocumentRepository
{

    /**
     *
     * @return array
     */
    public function getActive()
    {
        $query = $this->getQueryForGetActive();

        return $query->getQuery()->execute();
    }

    /**
     *
     * @return \Doctrine\ODM\MongoDB\Query\Builder
     */
    public function getQueryForGetActive()
    {
        $em = $this->getDocumentManager();
        $qb = $em->createQueryBuilder();

        $qb->field('published')->equals(LinkStatus::PUBLISHED);
        $qb->sort('createdAt', 'DESC');

        return $qb;
    }

    /**
     *
     * @return array
     */
    public function getActiveOrdered()
    {
        $query = $this->getQueryForGetActiveOrdered();

        return $query->getQuery()->execute();
    }

    /**
     *
     * @return \Doctrine\ODM\MongoDB\Query\Builder
     */
    public function getQueryForGetActiveOrdered()
    {
        $em = $this->getDocumentManager();
        $qb = $em->createQueryBuilder();

        $qb->field('published')->equals(LinkStatus::PUBLISHED);
        $qb->sort('name', 'ASC');

        return $qb;
    }

    /**
     *
     * @return \Doctrine\ODM\MongoDB\Query\Builder
     */
    public function getQueryBuilderForFilter()
    {
        $em = $this->getDocumentManager();
        $qb = $em->createQueryBuilder();

        $qb->sort('updatedAt', 'DESC');

        return $qb;
    }

    public function getOneBySlug($slug)
    {
        return $this->findOneBy(['slug' => $slug]);
    }

    /**
     * Count published elements from date
     *
     * @param  DateTime $date
     * @return int
     */
    public function countFromDate(DateTime $date)
    {
        $em = $this->getDocumentManager();
        return $em->createQueryBuilder()
            ->field('status')->equals(LinkStatus::PUBLISHED)
            ->field('createdAt')->gte($date)
            ->getQuery()->execute()->count()
            ;
    }

    /**
     *
     * @param  DateTime $date
     * @param  int      $limit
     * @return array
     */
    public function getMoreActiveFromDate(DateTime $date, $limit = 10)
    {
        // TODO: No ported to ODM
        $em = $this->getDocumentManager();
        $query = $em->createQuery(
            ' SELECT l ' .
            ' FROM BlogBundle:Link l ' .
            ' JOIN l.Post p ' .
            ' WHERE l.isPublished = ' . LinkStatus::PUBLISHED .
            ' AND l.createdAt >= :date ' .
            ' GROUP BY l ' .
            ' ORDER BY n DESC '
        )
            ->setParameter('date', $date)
            ->setMaxResults($limit);
    }
}
