<?php

namespace Desarrolla2\Bundle\BlogBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Desarrolla2\Bundle\BlogBundle\Document\PostView;
use Desarrolla2\Bundle\BlogBundle\Document\Post;
use DateTime;

/**
 * PostViewRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class PostViewRepository extends DocumentRepository
{
    /**
     * @param Post $post
     */
    public function add(Post $post)
    {
        $em = $this->getDocumentManager();

        $date = new DateTime();

        $click = $this->findOneBy(
            array(
                'postId' => $post->getId(),
                'date' => $date
            )
        );
        if (!$click) {
            $click = new PostView();
            $click->setPost($post);
            $click->setDate($date);
        }

        $click->increment();

        $em->persist($click);
        $em->flush();
    }
}
