<?php

namespace Desarrolla2\Bundle\BlogBundle\Document\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SearchQueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchQueryRepository extends EntityRepository
{
}
